### ISSUE TITLE
Upload to community site

### ISSUE THREAD

**Issue by tmatilai** [edelight/chef-solo-search#30]
Is there a reason why this is not uploaded to http://community.opscode.com/cookbooks? It would make it easier to use only released versions with for example Librarian or Berkshelf.

**Comment by tobami** [comment]
Yeah, we should definitely do it. Will do as soon as I have a moment

**Comment by patcon** [comment]
haha just came here to post that I'd done it and then found this thread:
http://community.opscode.com/cookbooks/chef-solo-search

Had been meaning to learn how to upload to the community site anyhow :)

**Comment by tmatilai** [comment]
Heh =)

**Comment by jwitrick** [comment]
So From the community site its appears to be broken.

The Libraries directory only contains search.rb and not the other subdirectories.

**Comment by patcon** [comment]
Balls. #firstcookbookpublishingFAIL

I'm flying to a Bitcoin conference today, but will try to fix it up when I get a sec :)

**Comment by tobami** [comment]
Hey @patcon that's great!

Just ping us when you get to fix it

**Comment by tmatilai** [comment]
Ah, I _just_ saw an Opscode ticket that cookbook "libraries" directory is not uploaded/downloaded recursively: http://tickets.opscode.com/browse/CHEF-672

Creating a tarball and uploading it via web interface _might_ work. The other option is to put all files into the "libraries" directory top level and handle the namespacing with filenames.

**Comment by tmatilai** [comment]
Maybe the version in the community site should be nuked? It does not work and it is not easy to see why. See for example #35.

Should we just flatten the libraries hierarchy?

**Comment by tknerr** [comment]
:+1: for fixing this

**Comment by patcon** [comment]
Hm. As a collaborator, I can't remove the cookbook completely. Only @tobami can

However, I tried uploading a new copy of v0.4.0 (identical to current one, but with missing files, without incrementing version), but I get this warning:
https://www.evernote.com/shard/s27/sh/15ca161d-5bc9-4c0b-8af8-0ea3f163602a/25c1dc8b6c764368a05eb4f636056cfd

It might work if we peel a new release, but don't think I have the power to make that call :) @tobami?

In all honesty, I'm still unsure specifically where the root cause would be with. Can anyone confirm, or link the relevant code? The linked issue [COOK-672](http://tickets.opscode.com/browse/CHEF-672) seems to focus on [code related to cookbook _loading_](https://github.com/opscode/chef/blob/master/lib/chef/cookbook/cookbook_version_loader.rb#L49), but not sure how that would play into stripping `libraries/` subdirs during upload to the community site...

Before we go any further, I'd recommend that we reproduce the process that somehow removed the subdirs. As I said, this was the first time I tried to package a cookbook, and it's possible I effed up somehow. I don't recall the exact steps I used either :/

I don't think I can step up on troubleshooting this right now, but I'll update if I do find time.

**Comment by tobami** [comment]
OK. I would definitely try to have a working release uploaded based on the current version. Only then do something radical like removing the directory hierarchy.

I will try to fix it this week.

**Comment by kennonkwok** [comment]
Any update on this?  The workaround is a bit of a pain with Berkshelf.

**Comment by kennonkwok** [comment]
releases on 9/19 fixed this for me.  thanks!

**Comment by michaelglass** [comment]
calling this "closed"
